---
- name: "Build Image and run container with ansible playbook"
  hosts: localhost
  tasks:
  - name: stop running container
    command: docker stop laravel-container
    ignore_errors: yes

  - name: remove stopped container
    command: docker rm laravel-container
    ignore_errors: yes

  - name: remove used image
    command: docker rmi mohamedsharaf123/laravel-app
    ignore_errors: yes

  - name: build docker image from dockerfile
    command: docker build -t mohamedsharaf123/laravel-app .
    args:
      chdir: /var/lib/jenkins/workspace/devops-pipline/DevOps-Pipeline-PHP/laravel-app

  - name: push image to dockerhub
    command: docker push mohamedsharaf123/laravel-app



  
